# See dbus.conf for why autorestart=false/startretries=0.
[program:wayvnc]
command=/etc/code-docker-chrome/wayvnc-service.sh
priority=30
autorestart=false
startretries=0
stdout_logfile=/var/log/%(program_name)s/stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/%(program_name)s/stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
